[tool.poetry]
name = "two"
version = "0.1.0"
description = ""
authors = ["Jason Barnett <J@sonBarnett.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
click = "^8.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
